-- 1 SOLVE THE BELOW QUESTIONS EACH QUESTION OF 2 MARKS 
  
-- i. WRITE AN SQL QUERY TO FETCH FULLNAME , SALARY , JOINING_DATE AND DEPARTMENT FROM 
-- WORKER TABLE. 
SELECT FIRST_NAME,SALARY,JOINING_DATE, DEPARTMENT FROM Worker;

--     ii.WRITE AN SQL QUERY TO FETCH ID , FULLNAME , SALARY AND DEPARTMENT WHOSE DEPARTMENT 
-- IS HR OR ADMIN 

SELECT WORKER_ID, CONCAT(FIRST_NAME," ",LAST_NAME) AS FULLNAME, SALARY FROM Worker WHERE DEPARTMENT IN ("HR","ADMIN");
--    iii.WRITE AN SQL QUERY TO FETCH ID , FULLNAME , SALARY WHOSE FIRST_NAME ENDS WITH 'a'

SELECT WORKER_ID,CONCAT(FIRST_NAME," ",LAST_NAME) AS FULLNAME, SALARY FROM Worker WHERE SUBSTR(FIRST_NAME,-1) = 'a';
--    iv. WRITE AN SQL QUERY TO FEACH ALL RECORDS OF WORKER TABLE WHO HAVE JOIN IN FEB 2020 

SELECT * FROM Worker WHERE YEAR(JOINING_DATE) = 2020 AND MONTH(JOINING_DATE) = 4;

--     V. WRITE AN SQL QUERY TO FEACH ALL RECORDS OF WORKER TABLE WHO HAVE SALARY >=50000 
-- AND <=100000.   
 
 SELECT * FROM worker WHERE SALARY BETWEEN 50000 AND 100000;

-- 2 SOLVE THE BELOW QUESTIONS EACH QUESTION OF 3 MARKS  
 
--    i. WRITE AN SQL QUERY TO DISPLAY NUMBER OF WORKER IN EACH DEPARTMENT ALONG WITH 
-- UNIQUE DEPARTMENT NAME 
SELECT COUNT(*) AS WORKER_NUMBER,DEPARTMENT FROM worker GROUP BY DEPARTMENT;

--    ii.WRITE AN SQL QUERY TO DISPLAY DEPARTMENT NAME AND TOTAL BONUS AMOUNT TO BE PAID IN 
-- EACH DEPARTMENT 

SELECT w.DEPARTMENT AS DEPARTMENT_NAME,SUM(b.BONUS_AMOUNT) AS TOTAL_BONUS_AMOUNT
FROM worker w INNER JOIN bonus b ON w.WORKER_ID = b.WORKER_REF_ID GROUP BY w.DEPARTMENT;

--   iii.WRITE AN SQL QUERY TO DISPALY THE FULLNAME , SALARY , TOTAL YEARS OF EXPERIANCE OF 
-- EACH WORKER  

SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS FULLNAME,
SALARY,
DATE_FORMAT(FROM_DAYS(DATEDIFF(NOW(),JOINING_DATE)),'%Y')+0 AS TOTAL_YEARS 
FROM worker;

--OR

SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS FULLNAME,
SALARY,
FLOOR((DATEDIFF(NOW(),JOINING_DATE))/365) AS TOTAL_YEARS
FROM worker;

--OR

SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS FULLNAME,
SALARY,
FLOOR(TIMESTAMPDIFF(YEAR,JOINING_DATE,NOW())) AS TOTAL_YEARS
FROM worker;

--    iv.WRITE AN SQL QUERY TO DISPALY THE DETAILS OF THE WORKER WHO IS MANAGER  

SELECT w.WORKER_ID, w.FIRST_NAME, w.LAST_NAME, w.SALARY, w.JOINING_DATE, w.DEPARTMENT, t.WORKER_TITLE
FROM worker w INNER JOIN  title t ON w.WORKER_ID = t.WORKER_REF_ID WHERE WORKER_TITLE='manager';
